[package]
name = "cryptopals"
version = "0.1.0"
authors = ["David Stainton <dstainton415@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.24"
rust-crypto = "^0.2"
rand = "^0.3"

[dev-dependencies]
rand = "^0.3"
